### ISSUE TITLE
Property List of RTEs returns list of NULL

### ISSUE THREAD

**Issue by pgregorynz** [umco/umbraco-property-list#9]
When using property list with RTEs, when the value is converted by the property value converter the result is all nulls.  The returned type is correct, `IEnumerable<IHtmlString>` but all the items in that list are null.

**Comment by leekelleher** [comment]
Hey @pgregorynz - thanks for raising this one.

I haven't had chance to dive into the code to debug this yet. (It'll most likely be late Thurs before I do).
Although I have my suspicions of what it might be... _I'm leaving some notes here, mostly for myself._

---

`TinyMceValueConverter` sets the `PropertyValueType` as `IHtmlString`, then [`ConvertSourceToObject` returns `HtmlString`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/PropertyEditors/ValueConverters/TinyMceValueConverter.cs#L32) ... which should be castable, but maybe it isn't? 🤔 

[Property List is using Umbraco's `TryConvertTo<T>`](https://github.com/umco/umbraco-property-list/blob/develop/src/Our.Umbraco.PropertyList/ValueConverters/PropertyListValueConverter.cs#L87) to perform the casting... so worth checking if `(HtmlString).TryConvertTo<IHtmlString>()` works as expected, or whether Property List needs to do extra work for interface-types?

**Comment by leekelleher** [comment]
Curses this has been playing on my mind... and it's lunch time.

It turns out that it is Umbraco's `TryConvertTo` methods doing different things, e.g.

The generic version works as expected...

```csharp
(new System.Web.HtmlString("foo")).TryConvertTo<System.Web.IHtmlString>().Success // is true
```

However the non-generic version fails...

```csharp
(new System.Web.HtmlString("foo")).TryConvertTo(typeof(System.Web.IHtmlString)).Success // is false
```

... and Property List is using the non-generic version, (since we only know the object-type at runtime).

Digging into Umbraco's `TryConvertTo<T>` (generic version) code, [this line](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/ObjectExtensions.cs#L84) will check if the non-generic version was successful, if not, it'd attempt a direct cast.  Which in this case explains why the generic version works and the non-generic version doesn't.

OK, where does this leave us?

1. Change Umbraco core so that `TinyMceValueConverter` return type is a `HtmlString`, and not an `IHtmlString`.  _(**not ideal**, too much work involved convincing people and waiting for release cycle and asking you to upgrade)_
2. Ask you to develop a custom TypeConverter that will cast an `HtmlString` to an `IHtmlString`, _(again, **not ideal**, throws the problem over your side of the fence ... and other people will ask me about this in future, etc)_
3. Add code to Property List to follow a similar pattern as Umbraco's `TryConvertTo<T>`, check for failure and attempt a direct cast.

While I don't think this is Property List's concern, _(I think it should be `TryConvertTo` responsibility),_ the last option will be frictionless.  I'll see what I can do. 😃

**Comment by leekelleher** [comment]
@pgregorynz I've added a fix for this. If you want to try it out, the latest package files from the CI build are here: <https://ci.appveyor.com/project/UMCO/umbraco-property-list/build/1.0.1.47/artifacts>

Preparing a release takes a little bit more time, I'll schedule a v1.0.1 release soon.

**Comment by leekelleher** [comment]
@pgregorynz Just to let you know that v1.0.1 is out! <https://github.com/umco/umbraco-property-list/releases/tag/1.0.1>
